version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 2000:80
    depends_on: 
      - db

  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: doctruyen
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-data:
    external: false